### ISSUE TITLE
NPE on render.

### ISSUE THREAD

**Issue by Claycorp** [asaskevich/SmartCursor#11]
```
[20:56:56] [Client thread/INFO] [STDERR]:   [com.asaskevich.smartcursor.RenderHandler:renderGameOverlay:242]: java.lang.NullPointerException
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:222)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.asaskevich.smartcursor.RenderHandler.renderGameOverlay(RenderHandler.java:128)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.eventhandler.ASMEventHandler_304_RenderHandler_renderGameOverlay_RenderGameOverlayEvent.invoke(.dynamic)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:699)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:155)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.main.Main.main(SourceFile:148)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:483)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:56:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by asaskevich** [comment]
Sorry for delay, can you provide more information, e.g. item/block you looking at?

**Comment by Claycorp** [comment]
Oh geez... I don't really remember. I think i was just looking at random items on the ground.

Ill try to reproduce or catch it when i see it next.

**Comment by asaskevich** [comment]
Okay, I hope that issue already fixed in current unreleased version. Just want be sure that all well. :)

**Comment by Claycorp** [comment]
I finally found one! Looking at beds. 
Also is there an ETA on the update? Looking forward to the new stuff!

**Comment by asaskevich** [comment]
Yeah, this issue also appears when player looks at the doubled blocks like door or bed. 

I hope that I will have more free time at the middle of May - somewhen in May will be new update. :smile:

**Comment by asaskevich** [comment]
@Claycorp need to check this again, maybe it doesn't make sense with the latest build for 1.12.2
